apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: credit-scoring-app-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Ashraf-Khabar/mlops-credit-scoring-k8s
    targetRevision: HEAD
    path: kubernetes/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true