FROM python:3.11-slim AS builder
WORKDIR /api
COPY requirements.txt .
RUN pip wheel --no-cache-dir --no-deps --wheel-dir /api/wheels -r requirements.txt

FROM python:3.11-slim
WORKDIR /api
COPY --from=builder /api/wheels /wheels
COPY --from=builder /api/requirements.txt .
RUN pip install --no-cache /wheels/*
COPY . .
EXPOSE 8000
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]