apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: credit-scoring-app-staging
  namespace: argocd
spec:
  project: cmsdp
  source:
    repoURL: https://github.com/Ashraf-Khabar/mlops-credit-scoring-k8s
    targetRevision: HEAD
    path: k8s/overlays/staging
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true