apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-credit
spec:
  selector:
    matchLabels:
      app: application-credit-AI
      tier: frontend
  template:
    metadata:
      labels:
        app: application-credit-AI
        tier: frontend
    spec:
      containers:
      - name: front
        image: ml-frontend:1.0.3
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 500m
            memory: 128Mi